### ISSUE TITLE
Set :ajax => false don't work

### ISSUE THREAD

**Issue by vladfreel** [bys-control/activeadmin-index_as_calendar#15]
Code:
```
ActiveAdmin.register CalendarCharter do
  permit_params :name, :email, :skipper, :phone, :boat_name, :start_time, :end_time, :message

  index_as_calendar ({:ajax => false}) do |item|
    {
        name: item.name,
        boat_name: item.boat_name,
    }
  end

    index do

      column :name
      column :email
      column :skipper
      column :phone
      column :boat_name
      column :start_time
      column :end_time
      column :message
      actions

    end
end
```

But the HTML whatever set  data-remote="true" :
`<a data-remote="true" href="/admin/calendar_charters?order=id_desc&amp;start_date=2018-10-01">Next</a>
`

**Comment by gbisheimer** [comment]
Hi @vladfreel.

I didn't have time to checkk it yet. Did you solve the problem?

**Comment by vladfreel** [comment]
Hi @gbisheimer 
Yes, I have required index_as_calendar/application in active_admin.coffee.js file, but it's wrong and I solved it by creating active_admin.js and require calendar there. My mistake.
