### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by gcrouillere** [bys-control/activeadmin-index_as_calendar#9]
Hi,

Thanks for this great plugin, it improved the admin experience of my app a lot ! 

I just struggled a bit with the install. Indeed the readme currently says to add @import "index_as_calendar/application" in the AA stylesheet... But I got a "unable to import index_as_calendar/application" message when re-launching the app. Until I found that your latest commit now import : +@import "fullcalendar" & @import "index_as_calendar/jquery.qtip.min";. Then I modified the imports with these and it worked.

Did I miss something ? Or the readme should be updated ?

thanks !

**Comment by gbisheimer** [comment]
Related to #10
